services:
  - type: web
    name: personal-website-frontend
    env: static
    rootDirectory: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDirectory: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
